adopted-ember-addons/ember-infinity

addon/components/infinity-loader.js, tests/unit/components/infinity-loader-test.js
The scrollable defaults to `window` if the option is not used.
Usage:
```
<div id="content">
{{#each model as |product|}}
<h1>{{product.name}}</h1>
<h2>{{product.description}}</h1>
{{/each}}
</div>
{{infinity-loader infinityModel=model scrollable="#content"}}
```
=> Add option to specify scrollable element

index.js, package.json
Was getting an ambiguous error `Missing template processor` when trying to boot my server after installing this add-on and had a hard time figuring out why. Turns out I'm using ember-cli 0.1.15 and need to upgrade.
=> Add descriptive error message when running ember-cli < 0.2.0

README.md
Command for addon installation is now without addon keyword.
``` #3598 [ENHANCEMENT] Replace install:addon with install, remove install:bower and install:npm @DanielOchoa ```
=> Fixes install command for new ember-cli

README.md
wasn't clear from the documentation that the server needed to include
the number of total pages in the response
https://github.com/hhff/ember-infinity/issues/12
I left the example data incomplete, since it would depend on each application.
Thanks!
=> adds json response to README.md

.editorconfig, .npmignore, .travis.yml, README.md, addon/mixins/route.js, bower.json, config/ember-try.js, package.json, testem.json, tests/acceptance/infinity-route-with-meta-test.js, tests/dummy/app/styles/app.css, tests/dummy/public/crossdomain.xml, tests/dummy/public/robots.txt, tests/unit/mixins/route-test.js
Currently this addon has the following request payload structure hardcoded
```js
{
per_page: 10,
page: 14
}
```
This PR allows customization of these two parameters, so that you could work with an API that expects to recieve something like
```js
{
per: 10,
p: 14
}
```
=> Allow customization of pagination API

.editorconfig, .npmignore, .travis.yml, README.md, addon/components/infinity-loader.js, addon/mixins/route.js, bower.json, config/ember-try.js, package.json, testem.json, tests/acceptance/infinity-route-with-meta-test.js, tests/acceptance/infinity-route-without-meta-test.js, tests/dummy/app/routes/category.js, tests/dummy/app/styles/app.css, tests/dummy/public/crossdomain.xml, tests/dummy/public/robots.txt, tests/helpers/start-app.js, tests/unit/mixins/route-test.js
Rewriting a couple of things to take advantage of new es6 language features.
=> ES6-ification

README.md, package.json
Demo app is now deployed to
http://hhff.github.io/ember-infinity/
I have added a link to the readme, and update ember-cli-github-pages to the newly tagged `v0.0.5` release
=> Update ember-cli-github-pages & Readme

.travis.yml, Brocfile.js, bower.json, config/ember-try.js, tests/dummy/app/styles/app.css
=> Babel.js polyfill in demo app

addon/mixins/route.js, tests/unit/mixins/route-test.js
=> uses the override properties when loading more

addon/components/infinity-loader.js, tests/unit/components/infinity-loader-test.js
In mobile view, the component is out of view on the first load. In desktop view, there is enough space for the component to load more a few times before being out of view. Currently the loader would not do anything because no scroll events occur.
This change will watch for pushes to the model and keep loading data if it is needed. The desktop view will fill up the screen on first page load.
=> keep loading until you are out of view

addon/components/infinity-loader.js, tests/unit/components/infinity-loader-test.js
If you maximize a small window and the loader comes into view, it will looks like it hangs. This will watch the resize event and check if in view. Paired with #44, maximizing a window will load as many times as necessary to fill up the page.
=> check if in view on resize events

README.md, addon/mixins/route.js, tests/unit/mixins/route-test.js
...to allow overrides in the case when more specialized munging/manipulation might be required.
For one part of our app that needs infinite scroll, we have a slightly non-traditional API that requires a more complicated merging of our initial data and subsequent requests. This extremely minor change makes it much easier for us to use `ember-infinity` in that case.
=> extract `model.pushObjects` to a method

README.md, addon/mixins/route.js, tests/unit/mixins/route-test.js
Hi @hhff, I've added the ability to pass in extra params that can be either static or dynamic. If the extra param is a property on the route, its value will be used for setting the extra param.
I hope this is an acceptable enhancement, I'm currently using this method to dynamically change the extra params I'm passing to the back-end.
=> Added the ability to pass in extra params that are (computed) properties

addon/mixins/route.js, tests/unit/mixins/route-test.js
I'm playing with a few interesting use cases, which involve using the "route.js" mixin on objects other than a route (i.e., an `Ember.Service` or something).
Allowing the store to be accessed is not a big problem -- I can just add a CP on this object
```js
store: computed({
get() {
return this.container.lookup('store:main');
}
}),
```
Unfortunately, accessing this CP directly via a `this.store`, before the CP's getter function has been invoked for the first time, will end up returning the computed property its self, rather than the property's value. 
This small change should maintain the existing use cases just fine, and also allow for potential usage that deviates from the well-traveled path.
=> Use Ember.get() to access store

addon/components/infinity-loader.js, index.js, package.json, tests/acceptance/infinity-route-with-embedded-route-test.js, tests/dummy/app/posts/route.js, tests/dummy/app/posts/show/controller.js, tests/dummy/app/posts/show/route.js, tests/dummy/app/posts/show/template.hbs, tests/dummy/app/posts/template.hbs, tests/dummy/app/router.js
In the project I'm working on currently we had problems with embedded routes and refreshing.
After refreshing the embedded route, the ember-infinity component would get re-initialized, without didInsertElement getting called. Thus the _setScrollable function was never called to set up the jquery object and we we're getting an error stating that "scrollable.height" is not a function.
I will add a test case in the course of the day to demonstrate the problem.
Cheers
Manuel Arno Korfmann
=> dont rely on didInsertElement setting up scrollable

README.md, addon/components/infinity-loader.js, app/templates/components/infinity-loader.hbs, blueprints/infinity-template/files/app/templates/components/infinity-loader.hbs, package.json, tests/integration/infinity-loader-test.js
Previously, the only possible loading indicators were `loadingText` and a CSS background image. This gives a much bigger range of possibilities, such as CSS animations with custom markup.
=> yield from the template

addon/mixins/route.js, tests/integration/infinity-loader-test.js, tests/unit/mixins/route-test.js
This branch is motivated in anticipation of some upcoming bugfixes. The state of the route is difficult to reason about due to numerous duplications and minor inconsistencies between the initial load and page 2+ loads. This branch attempts to bring them into line with each other. No tests have been changed, because no behavior has been changed.
=> Reduce duplication in route

bower.json
Per Ember 2.3.0-beta1 release notes (http://emberjs.com/blog/2015/11/16/ember-2-2-released.html), "ember-qunit 0.4.16+ is required for use with Ember 2.3." This upgrades ember-qunit which is all that's required to fix 2.3 compatibility. This fixes https://github.com/hhff/ember-infinity/issues/103
=> Upgrade ember-qunit

README.md, addon/mixins/route.js, tests/unit/mixins/route-test.js
This supercedes #77 with all changes made.
=> Add afterInfinityModel

tests/acceptance/infinity-route-with-embedded-route-test.js, tests/acceptance/infinity-route-with-meta-test.js, tests/acceptance/infinity-route-without-meta-test.js, tests/helpers/assert-acceptance-details.js, tests/helpers/fake-album-server.js, tests/unit/mixins/route-test.js
This should considerably improve code climate, and also just makes the tests easier to understand and for other contributors to use.
=> Improve tests

addon/mixins/route.js
I had the same problem mentioned in #93 issue. I'd like to use the mixin inside components, not in routes. Actually it would be nice to have reference to `this.get('store')` instead `this.store`. I don't have injected `store` to each component, so it's not possible to use `this.store` statement even I explicitly inject by `store: Ember.inject.service()`. Furthermore this change doesn't affect nothing more, so it only extend the configurability.
=> Changed references to this.store in order to allow using the mixin inside components

addon/mixins/route.js
The default behavior would swallow all errors that could occur while loading records and prints an obscure error message.
This is bad because:
-  When you read the error, you don't know what to do - there is no description of a "right" serverside configuration.
- When you override the `afterInfinityModel` hook, it won't display possible errors - this took me a few minutes to figure out what's wrong.
- When an error occurs while loading the resource (i.e 500 error), the default error ember handling will be ignored - The user is left in a broken UI state and you have no chance to fix this.
It's safer to leave the original error messages as is and don't swallow errors in favor of a more generic one.
=> Don't swallow errors when loading records

bower.json
Fixes Testem not running at all on a fresh install.
=> Pin jQuery to Ember.js compatible version

addon/components/infinity-loader.js
This should fix #100 and is corrected version of #138.
=> Prevent load more action when component is destroying or destroyed

README.md
=> Update README.md with requirements for the return value from afterInfinityModel

addon/mixins/route.js, tests/helpers/start-app.js, tests/unit/mixins/route-test.js
See: http://emberjs.com/blog/2016/04/11/ember-2-5-released.html#toc_code-ember-assign-code
=> Use Ember.assign over Ember.merge when possible

index.js, tests/dummy/app/routes/demo-scrollable.js, tests/dummy/app/routes/demo.js
We have ember-infinity as a dependency and on newer versions of Ember we're getting a deprecation warning due to `index.js` not calling super from init:
```
DEPRECATION: Overriding init without calling this._super is deprecated. Please call `this._super.init && this._super.init.apply(this, arguments);` addon: `ember-infinity`
at Function.Addon.lookup (/Users/mattdentremont/git/aiotv-admin/node_modules/ember-cli/lib/models/addon.js:896:27)
```
=> Use new super format from init to avoid deprecation warnings

addon/components/infinity-loader.js
Fixes #126 
Right now, if the scrollable is not the direct parent of the loader, then `position` will not give us what we want. Using `this.$().offset().top - this.get("_scrollable").offset().top` should always give us what we want though.
=> Fix loader with custom scrollable that never fires

addon/components/infinity-loader.js, addon/mixins/route.js
Fixes #150
Before calling `this._infinityLoad()`, double check that it's actually this route's loader which raised the `infinityLoad` action, otherwise bubble the `infinityLoad` action.
=> Only infinityLoad for this route's infinityModel

addon/mixins/route.js, tests/unit/mixins/route-test.js
Hi.
In my server (which is based on cursor pagination) I have to make sure no extra parameters are set.
Therefore I try to set perPageParam and pageParam to null.
Unfortunately I noticed the parameters still get added like this:
$URL?...&null=2&...
I write a patch to completely exclude parameters when the names are not set.
Hope you like it!
Paolo
=> Skip pagination parameters when set to null 

README.md
Update load-more-button docs to reflect changes from #174 
#174 requires that the `infinityModel` object be passed along with the `infinityLoad` action in order to work properly.
=> Update load-more-button docs

.jshintrc, addon/components/infinity-loader.js, addon/mixins/route.js, addon/utils.js, bower.json, ember-cli-build.js, index.js, package.json, tests/.jshintrc, tests/acceptance/infinity-custom-store-test.js, tests/acceptance/infinity-route-offset-trigger-test.js, tests/acceptance/infinity-route-with-embedded-route-test.js, tests/acceptance/infinity-route-with-meta-test.js, tests/acceptance/infinity-route-without-meta-test.js, tests/dummy/app/models/custom-model.js, tests/dummy/app/router.js, tests/dummy/app/routes/custom-store.js, tests/dummy/app/services/custom-store.js, tests/dummy/app/templates/custom-store.hbs, tests/dummy/config/environment.js, tests/helpers/module-for-acceptance.js, tests/unit/mixins/route-test.js
=> [EMBER]: upgrade to 2.8 and remove DS check

README.md
Added an example to the README of infinity-loader being triggered by a user action.
I had to do this in a project, and it may be obvious, but like most things Ember, I was tickled at how easily it was to make this happen.
In our project we stop automatic infinity loading each time the user changes their search parameters, and then ask them to initiate the infinite loading process again...
=> README note: user action triggers infinity-loader

addon/lib/infinity-model.js, addon/mixins/route.js, tests/unit/mixins/route-test.js
In the app I work on, we rely on the `meta` property of ember-data requests quite often. 
I realized today that infinity-models lose this meta data as they are `toArray`'ed versions of the original request. 
In order to persist the requests meta, I believe all we need to do is simply copy it over in the `_doUpdate` method of the `inifintyModel` route mixin. 
It is a simple one liner:
```javascript
_doUpdate(queryObject, infinityModel) {
const totalPages = queryObject.get(get(infinityModel, 'totalPagesParam'));
set(infinityModel, '_totalPages', totalPages);
set(infinityModel, 'meta', get(queryObject, 'meta')); // BOOM
return infinityModel.pushObjects(queryObject.toArray());
},
```
This PR removes some hanging chad white-space as well. 
I was not actually sure how to write a test for this …
=> Infinity model will persist original request meta on itself

package.json, tests/acceptance/infinity-route-test.js, tests/unit/mixins/route-test.js, yarn.lock
https://github.com/DockYard/ember-in-viewport/pull/153
=> Update in viewport to use one IO per viewport

package.json, yarn.lock
Was encountering timeouts in CI when using the DockYard/ember-in-viewport _version_
Instead I've set the version to the latest release to get it from the yarn registry.
=> Use released ember-in-viewport

addon/services/infinity.js, tests/acceptance/infinity-route-test.js, tests/dummy/app/routes/test-scrollable.js, tests/dummy/app/services/global.js
Injecting services on the extended infinity model was failing because the instance is created without a container. This seems like the right fix?
With the 1.0 API changes, _infinityModelLoaded_ and _infinityModelUpdated_ no longer have the context they did as members of the route. Now, an intermediary (e.g. a service) appears to be required to effect a change in the context of the route or controller, e.g.:
```js
import InfinityModel from 'ember-infinity/lib/infinity-model';
export default InfinityModel.extend({
infinityModelUpdated({ lastPageLoaded, totalPages }) {
if (totalPages > lastPageLoaded) {
// Hide footer until all records are loaded
set(this, 'memoryStorage.hasActiveInfiniteScroll', true);
}
}
});
```
```hbs
{{! app/templates/application.hbs}}
{{#unless …
```
=> Fix infinity model container so services can be injected on it

addon/components/infinity-loader.js
If the component was destroyed, but the callback was executed, it triggered an exception because `this.element` was not available.
=> Skip `_checkScrollableHeight` on destroyed element

README.md
=> Update README with JSON-API configuration

README.md
If you follow the basic usage service component approach and then attempt to implement button loading, the current instructions do not work because by default `this.infinityModel` does not return a promise.
=> Update README regarding button loading to work with default setup.

package.json
10 or > 12
8 is EOL.  Should have done this in the 2.0 release #401
=> Bump node in pkg.json

addon/components/infinity-loader.js, addon/templates/components/infinity-loader.hbs, app/templates/components/infinity-loader.hbs, app/templates/components/infinity-loader.js, package.json, tests/acceptance/infinity-route-test.js, tests/integration/infinity-loader-test.js, yarn.lock
This will get rid of the deprecation warning around `isVisible` as we will manage it explicitly.
close #415
=> Remove tagName from loader component

addon/components/infinity-loader.js, app/components/infinity-loader.js, app/templates/components/infinity-loader.js
Introducing a templated infinity-loader broke this. 
As an alternative, you can rename your custom template from `infinity-loader` to whatever.  In your component.js, you will have to extend ember-infinity's `infinity-loader`
```js
import InfinityLoader from 'ember-infinity/components/infinity-loader';
export default class MyLoader extends InfinityLoader();
```
close #417
=> Component already exists Error

addon/components/infinity-loader.js, addon/templates/components/infinity-loader.hbs
So after the refactor to remove `Component#isVisible` usage in https://github.com/ember-infinity/ember-infinity/pull/416 (which was in response to my own issue, so I feel partially responsible), the handling of the `infinityModel` being changed seems to have been broken.
Our use case is paginated search results, so we debounce creating a new infinity model when the user types something.
The first bug was that `_loadStatusDidChange` needed to be called initially for each model change, not just the first, or it could just sit visible on the page saying "Loading..." even if the new model only had one page.
The second bug was that the `_initialInfinityModelSetup` observer was cleared when the element was destroyed, which happens when the component hides itself once reaching infinity. I've …
=> Fix reuse of infinity-loader

addon/components/infinity-loader.js
While implementing ember-infinity in my project I noticed that the `<InfinityLoader>` would be in view but would not load new records. One simple way of testing this was to have an endpoint that returns 1 record per page. ember-infinity loads the first page, `<InfinityLoader>` remains in view, and no new records are loaded.
This PR contains the fix I came up with which resolve the issue.
`clientHeight` doesn't tell us anything about where the `viewPortElem` is located in the window relative to where `this.elem` is located. Using absolute values ensures that `_debounceScrolledToBottom()` is always called when the `<InfinityLoader>` component is in view.
=> Use abs position when checking if element is visible in viewport

package.json, yarn.lock
Resolves this deprecation with ember 3.27+:
> DEPRECATION: Usage of the Ember Global is deprecated. You should import the Ember module or the specific API instead.
>
> See https://deprecations.emberjs.com/v3.x/#toc_ember-global for details.
>
> Usages of the Ember Global may be caused by an outdated ember-cli-babel dependency. The following steps may help:
>
> * Upgrade the following addons to the latest version:
>   * ember-infinity
=> Upgrade ember-cli-babel to ^7.26.6

.github/workflows/ci.yml, addon/components/infinity-loader.js, package.json, yarn.lock
Resolves the following deprecations:
```
DEPRECATION: Using `run.cancel` has been deprecated. Instead, import the value directly from @ember/runloop:
import { cancel } from '@ember/runloop'; [deprecation id: deprecated-run-loop-and-computed-dot-access]
```
```
DEPRECATION: Using `run.debounce` has been deprecated. Instead, import the value directly from @ember/runloop:
import { debounce } from '@ember/runloop'; [deprecation id: deprecated-run-loop-and-computed-dot-access]
```
=> Import cancel, debounce directly from @ember/runloop

addon/components/infinity-loader.js, addon/templates/components/infinity-loader.hbs
This fixes the [`isVisible`](https://deprecations.emberjs.com/v3.x/#toc_ember-component-is-visible) deprecation.
I know https://github.com/ember-infinity/ember-infinity/pull/416 was supposed to get rid of this deprecation but I'm still getting it in Ember 3.28.
=> Fix isVisible deprecation

README.md, ember-infinity/package.json
As this is now a v2 addon it doesn't care what version of node your consuming app is using 👍
=> remove engine reference for Node 18

package.json, pnpm-lock.yaml, test-app/config/environment.js
because there were some PRs to #470 from other people's forks it confused github-changelog (and therefore release-plan) as to what was going on. 
This fixes the issue by relying on https://github.com/embroider-build/github-changelog/pull/23 👍
=> fix issue with github-changelog

ember-infinity/src/components/infinity-loader.js
If the `InfinityLoaderComponent` has already had `destroy` called then `infinityMomdel` will be `null`.
=> Account for isDestroying state on InfinityLoaderComponent

.github/workflows/plan-release.yml
From https://github.com/embroider-build/create-release-plan-setup/pull/123/
=> Update plan-release.yml to support labeling after merge

ember-infinity/src/components/infinity-loader.hbs, test-app/tests/integration/infinity-loader-test.js
In our application we allow changing filters that are passed to the infinity model, so we create a new infinity model. However, when the current model has reached infinity, updating the infinity model does not update within the infinity loader, so the new model does not load more pages.
I added a test that reflects this, and fixed it by adding an empty div when not shown, to host the `{{did-update}}`. Not an ideal solution, so let me know if there are other solutions 👍
=> Fix infinity-loader not updating model when infinity reached
