README.md
=> Fixed h2 tag

README.md, addon/mixins/route.js
Infinity model expects that user will set it as model on controller. I believe this should be handled internally or at least settable. I don't like the code, but can't figure out way how to make it cleaner. If you would like to merge it anyway, give me echo and I'll update readme file.
=> Adding ability to change default model path

addon/mixins/route.js, package.json
about issue #25 
sorry not so familiar with github
=> fixed wrong error message

README.md
* dependency versions (david-dm.org)
* devDependency versions (david-dm.org)
* code climate
=> More badges for readme

addon/components/infinity-loader.js, tests/unit/components/infinity-loader-test.js
Also added and additional _unbindEvent call in _bindEvent, since @cprussin also reported overly lavishly bound events.
=> [Bugfix] Preserving scrollable on subsequent rerenders - reported by @cprussin

tests/unit/mixins/route-test.js
Cleans up the route test and makes the setup/expectations clearer in each test case.
=> Refactor Route test

README.md
=> Update README, add Infinity Button Component

package.json
=> update htmlbars dependency

tests/unit/components/infinity-loader-test.js
Fixed failing test:
```
not ok 48 PhantomJS 1.9 - JSHint - unit/components: unit/components/infinity-loader-test.js should pass jshint
---
actual: >
false
expected: >
true
message: >
unit/components/infinity-loader-test.js should pass jshint.
unit/components/infinity-loader-test.js: line 169, col 16, Don't make functions within a loop.
1 error
Log: |
...
```
=> Fixed failing test `Don't make functions within a loop.`

addon/components/infinity-loader.js
Resolves FastBoot error as described in #186.
=> Ensures no FastBoot environment before loading more records

README.md
After #147, I figured this would be a really useful feature to document.
Cheers 😃.
=> Document how to leave off parameters

README.md
=> Fix documentation examples for `infinityModelUpdated` and `infinityModelLoaded`

README.md
Back at it again with the syntax highlighting
=> Update syntax highlighting in README

README.md
@hhff Should we add this line to the README indicating that we are moving towards a 1-0 release?
=> [README]: update readme with note about 1-0 branch

README.md, addon/mixins/bound-params.js, addon/mixins/route.js, addon/utils.js, tests/unit/mixins/route-test.js
=> Extending Infinity Model

README.md, addon/components/infinity-loader.js, tests/unit/components/infinity-loader-test.js
Adds hideOnInfinity support to the infinity-loader component
* Changes the destroyOnInfinity infinity-loader property to hideOnInfinity
* When set to true, the infinity-loader will hide itself
* Adds notes to the readme
* Adds tests for when the hideOnInfinity is set, and not set.
closes #243
=> Change destroyOnInfinity to hideOnInfinity

README.md
@williamweckl I'm sure you have already gotten around to testing scrolling but lmk what you think!
close #241
=> update readme with testing examples

package-lock.json, package.json
tag at 2.2.0.  Updates to in-viewport to come.
=> set in-viewport 2.2

package-lock.json, package.json
=> move in-viewport to deps

.travis.yml, config/ember-try.js, ember-cli-build.js, package-lock.json, package.json, tests/acceptance/infinity-custom-store-test.js, tests/acceptance/infinity-route-offset-trigger-test.js, tests/acceptance/infinity-route-with-embedded-route-test.js, tests/acceptance/infinity-route-with-meta-test.js, tests/acceptance/infinity-route-with-non-blocking-model-test.js, tests/acceptance/infinity-route-without-meta-test.js, tests/dummy/config/targets.js, tests/helpers/assert-acceptance-details.js, yarn.lock
Upgrade to ember to 3.0 and upgrade acceptance tests to new qunit api.
=> update acceptance test and move to 3.0.0

README.md, tests/dummy/app/routes/demo-scrollable.js, tests/dummy/app/services/global.js, tests/unit/mixins/route-test.js
@scottkidder Would love to hear your thoughts on this PR!
Ref #263
=> Fix extended model in README

README.md, tests/dummy/app/templates/demo-scrollable.hbs, tests/dummy/app/templates/demo.hbs
https://emberjs.com/deprecations/v2.x/#toc_controller-content-alias
=> remove deprecated content alias in 2.17 in dummy app

package-lock.json, package.json
=> upgrade ember-in-viewport

addon/services/infinity-loader.js, tests/acceptance/infinity-load-previous-test.js, tests/acceptance/infinity-route-test.js, tests/dummy/app/controllers/test-scrollable.js, tests/dummy/app/routes/test-scrollable.js, tests/dummy/app/styles/app.css, tests/dummy/app/templates/test-scrollable.hbs
=> Ensure keep loading records until fill screen close #275

README.md, addon/lib/infinity-model.js
=> Change from alias to oneWay

.travis.yml, README.md, addon/lib/infinity-model.js, addon/mixins/route.js, addon/services/infinity.js, tests/unit/mixins/route-test.js
=> fix after model hook

README.md, addon/components/infinity-loader.js, addon/lib/infinity-model.js, addon/mixins/route.js, addon/services/infinity.js, tests/acceptance/infinity-route-test.js, tests/dummy/app/posts/route.js, tests/dummy/app/routes/category.js, tests/dummy/app/routes/custom-store.js, tests/dummy/app/routes/demo-scrollable.js, tests/dummy/app/routes/demo.js, tests/dummy/app/routes/home.js, tests/dummy/app/routes/load-previous.js, tests/dummy/app/routes/nested.js, tests/dummy/app/routes/non-blocking-model.js, tests/dummy/app/routes/test-scrollable.js, tests/dummy/app/templates/components/list-items.hbs, tests/dummy/app/templates/nested.hbs, tests/unit/mixins/route-test.js
@hhff @williamweckl merge into #287
=> Move store work to infinity model

README.md, addon/lib/infinity-model.js, addon/mixins/route.js, addon/services/infinity.js, tests/dummy/app/routes/demo-scrollable.js, tests/unit/mixins/route-test.js
@wuron Could you try out this branch when you get a minute and lmk if it fixes the issue?  Thanks a bunch!
close #298 #292 
Potentially supercede #294 but not totally sure sure which one we want to do.  I liked most of it so need to compare and contrast.
=> fix after infinity hook

addon/components/infinity-loader.js, addon/services/infinity.js, tests/acceptance/infinity-route-with-non-blocking-model-test.js, tests/dummy/app/components/top-component.js, tests/dummy/app/router.js, tests/dummy/app/routes/nested-component.js, tests/dummy/app/templates/components/list-items.hbs, tests/dummy/app/templates/components/top-component.hbs, tests/dummy/app/templates/nested-component.hbs
=> Fix component loading by making type of returned value transparent

package.json, yarn.lock
Points ember-in-viewport at master instead of a branch.
=> Update deps to 3.3 and in-viewport

README.md, addon/components/infinity-loader.js, tests/acceptance/infinity-route-test.js, tests/dummy/app/router.js, tests/dummy/app/routes/extended.js, tests/dummy/app/templates/extended.hbs, tests/integration/infinity-loader-test.js, yarn.lock
=> Fix first load hide on infinity

addon/components/infinity-loader.js, addon/lib/infinity-model.js, addon/services/infinity.js, app/templates/components/infinity-loader.hbs, tests/acceptance/infinity-route-with-non-blocking-model-test.js, tests/integration/infinity-loader-test.js
@Duder-onomy Hey!  👋 When you have a moment, do you think you could try this out and lmk how it goes?
close #313
=> Fix loader with non blocking models

package.json, tests/dummy/app/controllers/load-previous.js, tests/dummy/app/controllers/test-scrollable.js, yarn.lock
https://github.com/DockYard/ember-in-viewport/pull/157/files
=> Update ember-in-viewport to 1.2

package.json, yarn.lock
=> Update in-viewport to 3.1.2

package.json, yarn.lock
https://github.com/DockYard/ember-in-viewport/pull/162
Will point to a version once I verify it works
Thanks @kevinansfield!!!  Getting this one in quick b/c it is not a good 🐛
=> fix error when sizzle adds properties to loader

.eslintignore, .eslintrc.js, .npmignore, .template-lintrc.js, .travis.yml, README.md, addon/lib/infinity-model.js, package.json, tests/.eslintrc.js, tests/dummy/app/routes/load-previous.js, tests/dummy/app/templates/demo-scrollable.hbs, yarn.lock
Also improves readme + placeholder for ember-concurrency addition to docs
=> Update to 3.4

package.json, yarn.lock
https://github.com/DockYard/ember-in-viewport/pull/167
=> fix minor bug in calc r/l scrolling

addon/components/infinity-loader.js, tests/acceptance/infinity-route-test.js, tests/integration/infinity-loader-test.js
@ryedeer Lmk what you think and if it fixes the issue you are looking at (basically just copied your fix 🙇)
close #331
=> Watch model on infinity-loader component and recompute when replaced

addon/services/infinity.js
Will target v `1.2.6`
close #333 
https://developer.mozilla.org/en/docs/Web/API/document/scrollingElement
@johncalvinyoung Put up a review quickly for the bug you found.  Great find!
=> Use scollingElement for cross browser support for scrolling area

.eslintignore, .travis.yml, package.json, yarn.lock
Swapping out some internals for a general npm package.
https://github.com/snewcomer/intersection-observer-admin
=> Use intersection-observer-admin for managing Intersection Observers

package.json, yarn.lock
https://github.com/DockYard/ember-in-viewport/releases/tag/v3.2.0
=> Update to 3.2 in-viewport

package.json, yarn.lock
https://github.com/DockYard/ember-in-viewport/pull/175
=> Update to 3.2.2 in-viewport (bugfix for raf)

README.md
=> Fix README for infinity button

addon/services/infinity.js, tests/unit/services/infinity-test.js
=> Allow nested object to cache

blueprints/infinity-template/files/app/templates/components/infinity-loader.hbs
=> Mirror default component template in blueprint

addon/services/infinity.js, tests/unit/services/infinity-test.js
=> Only generate unique hash from allowed keys

README.md, addon/lib/infinity-model.js, addon/services/infinity.js
We aren't handling error states very well either so need to figure that out.
=> Minor improvements to docs and make `isLoaded` && `isError` public

README.md, addon/lib/infinity-model.js, addon/services/infinity.js
=> loadingMore public

addon/components/infinity-loader.js, tests/integration/infinity-loader-test.js
=> Infinity Loader improvement

package-lock.json, package.json
https://github.com/snewcomer/intersection-observer-admin/pull/6
=> Fix small bugs in ember-in-viewport

addon/services/infinity.js
=> Optional store injection

addon/components/infinity-loader.js
=> Show loader when reachedInfinity changes

addon/components/infinity-loader.js, tests/acceptance/infinity-custom-store-test.js, tests/dummy/app/routes/custom-store.js, tests/dummy/app/routes/extended.js, tests/dummy/app/services/custom-store.js
=> Add another custom store test

addon/components/infinity-loader.js
=> Add some protection against destroying component and setters

README.md
=> fix: update canLoadMore example to ES6 class

addon/templates/components/infinity-loader.hbs, blueprints/infinity-template/files/app/templates/components/infinity-loader.hbs
https://github.com/emberjs/rfcs/pull/689
=> Fix hasBlock deprecation (RFC #689)

package.json, yarn.lock
ref https://github.com/ember-infinity/ember-infinity/issues/446#issuecomment-829533415
=> [Deps]: bump in-viewport 3.10.2

package.json, patches/github-changelog@1.0.1.patch, pnpm-lock.yaml
sorry about all the noise to anyone watching this 🙈
=> swap override for patched package
